server.port: 8080
server.error.include-stacktrace: never

spring:
  datasource:
    url: jdbc:mysql://0.0.0.0:3306/parking_db
    username: root
    password: root
  #security:
    #user:
      #name: user
      #password: 123
      #roles: "USER"
  jpa:
    hibernate:
      show-sql: true

messages.parking-not-found: Parking nao encontrado
messages.operation-already-done: Operacao ja realizada
messages.id-invalido: Id Invalido

